/**
 * Famous countries → provinces / states / regions
 * (same 省队 flow: pick country, then province team)
 */
export const COUNTRIES = {
  China: [
    'Beijing',
    'Tianjin',
    'Hebei',
    'Shanxi',
    'Inner Mongolia',
    'Liaoning',
    'Jilin',
    'Heilongjiang',
    'Shanghai',
    'Jiangsu',
    'Zhejiang',
    'Anhui',
    'Fujian',
    'Jiangxi',
    'Shandong',
    'Henan',
    'Hubei',
    'Hunan',
    'Guangdong',
    'Guangxi',
    'Hainan',
    'Chongqing',
    'Sichuan',
    'Guizhou',
    'Yunnan',
    'Tibet',
    'Shaanxi',
    'Gansu',
    'Qinghai',
    'Ningxia',
    'Xinjiang',
  ],
  Taiwan: [
    'Taipei',
    'New Taipei',
    'Taoyuan',
    'Taichung',
    'Tainan',
    'Kaohsiung',
    'Keelung',
    'Hsinchu City',
    'Hsinchu County',
    'Chiayi City',
    'Chiayi County',
    'Changhua',
    'Yunlin',
    'Nantou',
    'Pingtung',
    'Yilan',
    'Hualien',
    'Taitung',
    'Penghu',
    'Kinmen',
    'Lienchiang',
  ],
  'Hong Kong': [
    'Central and Western',
    'Wan Chai',
    'Eastern',
    'Southern',
    'Yau Tsim Mong',
    'Sham Shui Po',
    'Kowloon City',
    'Wong Tai Sin',
    'Kwun Tong',
    'Kwai Tsing',
    'Tsuen Wan',
    'Tuen Mun',
    'Yuen Long',
    'North',
    'Tai Po',
    'Sha Tin',
    'Sai Kung',
    'Islands',
  ],
  Macao: ['Macao Peninsula', 'Taipa', 'Coloane', 'Cotai'],
  Cambodia: [
    'Phnom Penh',
    'Banteay Meanchey',
    'Battambang',
    'Kampong Cham',
    'Kampong Chhnang',
    'Kampong Speu',
    'Kampong Thom',
    'Kampot',
    'Kandal',
    'Koh Kong',
    'Kratie',
    'Mondulkiri',
    'Oddar Meanchey',
    'Pailin',
    'Preah Vihear',
    'Prey Veng',
    'Pursat',
    'Ratanakiri',
    'Siem Reap',
    'Preah Sihanouk',
    'Stung Treng',
    'Svay Rieng',
    'Takeo',
    'Tbong Khmum',
    'Kep',
  ],
  'United States': [
    'California',
    'Texas',
    'Florida',
    'New York',
    'Pennsylvania',
    'Illinois',
    'Ohio',
    'Georgia',
    'North Carolina',
    'Michigan',
    'New Jersey',
    'Virginia',
    'Washington',
    'Arizona',
    'Massachusetts',
    'Tennessee',
    'Indiana',
    'Missouri',
    'Maryland',
    'Wisconsin',
    'Colorado',
    'Minnesota',
    'South Carolina',
    'Alabama',
    'Louisiana',
    'Kentucky',
    'Oregon',
    'Oklahoma',
    'Connecticut',
    'Utah',
    'Iowa',
    'Nevada',
    'Arkansas',
    'Mississippi',
    'Kansas',
    'New Mexico',
    'Nebraska',
    'Idaho',
    'West Virginia',
    'Hawaii',
    'New Hampshire',
    'Maine',
    'Montana',
    'Rhode Island',
    'Delaware',
    'South Dakota',
    'North Dakota',
    'Alaska',
    'Vermont',
    'Wyoming',
  ],
  India: [
    'Maharashtra',
    'Uttar Pradesh',
    'Gujarat',
    'Karnataka',
    'Tamil Nadu',
    'West Bengal',
    'Rajasthan',
    'Kerala',
    'Punjab',
    'Haryana',
    'Delhi',
    'Telangana',
    'Andhra Pradesh',
    'Madhya Pradesh',
    'Bihar',
    'Odisha',
    'Assam',
    'Jharkhand',
    'Chhattisgarh',
    'Goa',
  ],
  Pakistan: [
    'Punjab',
    'Sindh',
    'Khyber Pakhtunkhwa',
    'Balochistan',
    'Islamabad',
    'Gilgit-Baltistan',
    'Azad Kashmir',
  ],
  Japan: [
    'Tokyo',
    'Osaka',
    'Kanagawa',
    'Aichi',
    'Hokkaido',
    'Fukuoka',
    'Hyogo',
    'Kyoto',
    'Saitama',
    'Chiba',
    'Hiroshima',
    'Okinawa',
  ],
  'South Korea': [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Ulsan',
    'Gyeonggi',
    'Gangwon',
    'Jeju',
  ],
  'United Kingdom': [
    'England',
    'Scotland',
    'Wales',
    'Northern Ireland',
    'London',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Glasgow',
    'Edinburgh',
  ],
  Canada: [
    'Ontario',
    'Quebec',
    'British Columbia',
    'Alberta',
    'Manitoba',
    'Saskatchewan',
    'Nova Scotia',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Prince Edward Island',
  ],
  Australia: [
    'New South Wales',
    'Victoria',
    'Queensland',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Australian Capital Territory',
    'Northern Territory',
  ],
  Germany: [
    'Bavaria',
    'Berlin',
    'Hamburg',
    'North Rhine-Westphalia',
    'Baden-Württemberg',
    'Hesse',
    'Saxony',
    'Lower Saxony',
    'Rhineland-Palatinate',
    'Brandenburg',
  ],
  France: [
    'Île-de-France',
    'Provence-Alpes-Côte d\'Azur',
    'Auvergne-Rhône-Alpes',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Hauts-de-France',
    'Grand Est',
    'Brittany',
    'Normandy',
    'Corsica',
  ],
  Italy: [
    'Lazio',
    'Lombardy',
    'Campania',
    'Sicily',
    'Veneto',
    'Tuscany',
    'Piedmont',
    'Emilia-Romagna',
    'Sardinia',
    'Liguria',
  ],
  Spain: [
    'Madrid',
    'Catalonia',
    'Andalusia',
    'Valencia',
    'Galicia',
    'Basque Country',
    'Castile and León',
    'Canary Islands',
    'Balearic Islands',
    'Murcia',
  ],
  Brazil: [
    'São Paulo',
    'Rio de Janeiro',
    'Minas Gerais',
    'Bahia',
    'Paraná',
    'Rio Grande do Sul',
    'Pernambuco',
    'Ceará',
    'Amazonas',
    'Federal District',
  ],
  Mexico: [
    'Mexico City',
    'Jalisco',
    'Nuevo León',
    'Puebla',
    'Guanajuato',
    'Yucatán',
    'Quintana Roo',
    'Baja California',
    'Chihuahua',
    'Veracruz',
  ],
  Russia: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
    'Samara',
    'Krasnodar',
    'Vladivostok',
    'Sochi',
  ],
  Indonesia: [
    'Jakarta',
    'West Java',
    'East Java',
    'Central Java',
    'Bali',
    'North Sumatra',
    'South Sulawesi',
    'Banten',
    'Yogyakarta',
    'Riau',
  ],
  Turkey: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Antalya',
    'Bursa',
    'Adana',
    'Gaziantep',
    'Konya',
    'Mersin',
    'Trabzon',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Makkah',
    'Madinah',
    'Eastern Province',
    'Asir',
    'Tabuk',
    'Hail',
    'Najran',
    'Jazan',
    'Al-Qassim',
  ],
  UAE: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Fujairah',
    'Umm Al Quwain',
  ],
  Egypt: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Luxor',
    'Aswan',
    'Port Said',
    'Suez',
    'Dakahlia',
    'Sharqia',
    'Red Sea',
  ],
  'South Africa': [
    'Gauteng',
    'Western Cape',
    'KwaZulu-Natal',
    'Eastern Cape',
    'Free State',
    'Limpopo',
    'Mpumalanga',
    'North West',
    'Northern Cape',
  ],
  Nigeria: [
    'Lagos',
    'Abuja',
    'Kano',
    'Rivers',
    'Oyo',
    'Kaduna',
    'Delta',
    'Ogun',
    'Enugu',
    'Anambra',
  ],
  Argentina: [
    'Buenos Aires',
    'Córdoba',
    'Santa Fe',
    'Mendoza',
    'Tucumán',
    'Salta',
    'Entre Ríos',
    'Misiones',
    'Chaco',
    'Neuquén',
  ],
  Thailand: [
    'Bangkok',
    'Chiang Mai',
    'Phuket',
    'Chonburi',
    'Nakhon Ratchasima',
    'Khon Kaen',
    'Songkhla',
    'Ayutthaya',
    'Pattaya',
    'Krabi',
  ],
  Vietnam: [
    'Hanoi',
    'Ho Chi Minh City',
    'Da Nang',
    'Hai Phong',
    'Can Tho',
    'Hue',
    'Nha Trang',
    'Quang Ninh',
    'Binh Duong',
    'Dong Nai',
  ],
  Philippines: [
    'Metro Manila',
    'Cebu',
    'Davao',
    'Iloilo',
    'Pampanga',
    'Cavite',
    'Laguna',
    'Bulacan',
    'Batangas',
    'Rizal',
  ],
  Malaysia: [
    'Johor',
    'Kedah',
    'Kelantan',
    'Melaka',
    'Negeri Sembilan',
    'Pahang',
    'Penang',
    'Perak',
    'Perlis',
    'Sabah',
    'Sarawak',
    'Selangor',
    'Terengganu',
    'Kuala Lumpur',
    'Labuan',
    'Putrajaya',
  ],
  Singapore: ['Singapore'],
  Bangladesh: [
    'Dhaka',
    'Chittagong',
    'Khulna',
    'Rajshahi',
    'Sylhet',
    'Barisal',
    'Rangpur',
    'Mymensingh',
  ],
  Netherlands: [
    'North Holland',
    'South Holland',
    'Utrecht',
    'North Brabant',
    'Gelderland',
    'Limburg',
    'Overijssel',
    'Friesland',
    'Groningen',
    'Flevoland',
  ],
  Sweden: [
    'Stockholm',
    'Västra Götaland',
    'Skåne',
    'Uppsala',
    'Östergötland',
    'Jönköping',
    'Halland',
    'Örebro',
  ],
  Switzerland: [
    'Zurich',
    'Geneva',
    'Bern',
    'Vaud',
    'Basel',
    'Lucerne',
    'Ticino',
    'St. Gallen',
  ],
  Poland: [
    'Masovia',
    'Lesser Poland',
    'Silesia',
    'Greater Poland',
    'Pomerania',
    'Lower Silesia',
    'Lublin',
    'Łódź',
  ],
  'New Zealand': [
    'Auckland',
    'Wellington',
    'Canterbury',
    'Waikato',
    'Otago',
    'Bay of Plenty',
    'Manawatū-Whanganui',
    'Hawke\'s Bay',
  ],
} as const;

export type CountryId = keyof typeof COUNTRIES;
export type RegionId = (typeof COUNTRIES)[CountryId][number];

/** China first (game origin), then A–Z. */
export const COUNTRY_IDS: CountryId[] = [
  'China',
  ...((Object.keys(COUNTRIES) as CountryId[]).filter((c) => c !== 'China').sort()),
];

export function provincesFor(country: CountryId): readonly RegionId[] {
  return COUNTRIES[country] as readonly RegionId[];
}

export function findCountryForProvince(province: string): CountryId | null {
  for (const c of COUNTRY_IDS) {
    if ((COUNTRIES[c] as readonly string[]).includes(province)) return c;
  }
  return null;
}

export function teamKey(country: CountryId, region: RegionId): string {
  return `${country}::${region}`;
}

export function parseTeamKey(key: string): { country: string; region: string } | null {
  const i = key.indexOf('::');
  if (i < 0) return null;
  return { country: key.slice(0, i), region: key.slice(i + 2) };
}
